apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: integration-tests-example

spec:
  type: ClusterIP
  selector:
    integration: database
  ports:
    - port: 5432
      targetPort: 5432